<h1 class="col-xs-12">Users</h1>

<table class="table table-striped">

	<thead>
		<tr>	
			<th>#</th>
			<th>Name</th>
			<th>Email</th>
			<th>Registered On</th>
			<th>Actions</th>
		</tr>
	</thead>

	<tbody>

		<?php foreach($this->users as $user): ?>

			<tr>

				<td><?= $user->getId() ?></td>
				<td><?= $user->getName() ?></td>
				<td><?= $user->getEmail() ?></td>
				<td><?= $user->getDateRegistered()->format('d/m/Y') ?></td>
				<td>

					<a class="btn btn-default" href="<?= $this->url('admin/wildcard', ['controller' => 'user', 'action' => 'edit', 'id' => $user->getId()]) ?>">Edit</a>
					<a class="btn btn-danger" href="<?= $this->url('admin/wildcard', ['controller' => 'user', 'action' => 'delete', 'id' => $user->getId()]) ?>">Edit</a>

				</td>

			</tr>

		<?php endforeach ?>

	</tbody>

</table>