<div class="row">

	<h1 class="col-xs-12">Admins</h1>

</div>

<div class="row">

	<table class="col-xs-12 table table-striped">

		<thead>
			<tr>
				<th>#</th>
				<th>Name</th>
				<th>Email</th>
				<th>Registered On</th>
				<th>Actions</th>
			</tr>
		</thead>

		<tbody>

			<?php foreach($this->entities as $entity): ?>

				<tr>

					<td><?= $entity->getId() ?></td>
					<td><?= $entity->getName() ?></td>
					<td><?= $entity->getEmail() ?></td>
					<td><?= $entity->getDateRegistered()->format('d/m/Y') ?></td>
					<td>

						<a class="btn btn-default" href="<?= $this->url('admin/wildcard', ['controller' => 'admin', 'action' => 'edit', 'id' => $entity->getId()]) ?>">Edit</a>
						<a class="btn btn-danger" href="<?= $this->url('admin/wildcard', ['controller' => 'admin', 'action' => 'delete', 'id' => $entity->getId()]) ?>">Delete</a>

					</td>

				</tr>

			<?php endforeach ?>

		</tbody>

	</table>

</div>

<div class="row">

	<a class="btn btn-primary" href="<?= $this->url('admin', ['controller' => 'admin', 'action' => 'add']) ?>">Add</a>

</div>